services:
  - type: web
    name: aliexpress-scraper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: FLASK_ENV
        value: production
    autoDeploy: true
